name: oncopredict-ai
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.10
  - pip=23.0
  
  # Scientific computing
  - numpy=1.22.*
  - pandas=1.4.*
  - scipy=1.8.*
  
  # Machine Learning
  - scikit-learn=1.0.*
  - xgboost=1.5.*
  - lightgbm=3.3.*
  
  # Visualization
  - matplotlib=3.5.*
  - seaborn=0.11.*
  - plotly=5.6.*
  
  # Jupyter
  - jupyter=1.0.*
  - ipykernel=6.9.*
  
  # Development
  - pytest=7.0.*
  - black=22.1.*
  - flake8=4.0.*
  - isort=5.10.*
  
  # Utils
  - pyyaml=6.0
  - joblib=1.1.*
  
  # Pip dependencies
  - pip:
    # ML libraries not in conda
    - kagglehub>=0.3.0
    - prophet>=1.0.0
    
    # Documentation
    - sphinx>=4.4.0
    - sphinx-rtd-theme>=1.0.0
    
    # Development
    - pre-commit>=2.17.0
